# This is a basic workflow to help you get started with Actions

name: cicd-for-app

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  ################################################# Job called "test"
  test:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://github.com

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out source code
        uses: actions/checkout@v3

      # Set up python
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
      - name: Run pytest
        run: |
          coverage run --source=app/modules/ -m pytest -v tests && coverage report -m
      - name: Run pylinting
        run: |
          pylint app/

  ################################################# Job called "build"
  build:

    # The type of runner that the job will run on
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://github.com

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out source code
        uses: actions/checkout@v3

      # Generate major, minor tag
      - name: Get major and minor versions
        run: |
          echo "MINOR_VERSION_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "MAJOR_VERSION_TAG=$(cat version)" >> $GITHUB_ENV
          echo "APP_NAME=app-test" >> $GITHUB_ENV

      # Generate tag (must be done on a separate step, otherwise it fails)
      - name: Generate tag
        run: |
          echo "VERSION_TAG=${{env.MAJOR_VERSION_TAG}}.${{env.MINOR_VERSION_TAG}}" >> $GITHUB_ENV

      - name: Use tag
        run: |
          echo "Current version of app ${{env.APP_NAME}} is: ${{env.VERSION_TAG}}"

      # Login to Azure
      # https://learn.microsoft.com/en-us/azure/container-instances/container-instances-github-action
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Build and push docker image
      - name: Build and push docker image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.SERVICE_PRINCIPAL_CLIENTID }}
          password: ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{env.APP_NAME}}:${{env.APP_NAME}}_v${{env.VERSION_TAG}}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{env.APP_NAME}}:${{env.APP_NAME}}_v${{env.VERSION_TAG}}
